version: "3.9"

services:
  poll:
    build: ./poll
    ports:
      - "5000:80"
    environment:
      - REDIS_HOST=redis
    networks:
      - poll-network

  result:
    build: ./result
    ports:
      - "5001:80"
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432 
      - POSTGRES_DB=mydb 
    networks:
      - result-network

  worker:
    build: ./worker
    environment:
      - REDIS_HOST=redis
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432 
      - POSTGRES_DB=mydb 
    depends_on:
      - redis
      - db
    networks:
      - worker-network

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    networks:
      - poll-network
      - worker-network

  db:
    image: postgres:16
    environment:
      - POSTGRES_DB=mydb
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    networks:
      - result-network
      - worker-network

volumes:
  db-data:

networks:
  poll-network:
  result-network:
  worker-network:
